/* SAGS shared form layout · generated by AD · do not edit by hand */
window.SAGS_PUBLISHED_FORM_LAYOUT={
  "schema": 3,
  "build": "V3.75",
  "publishedAt": 1787395371348,
  "forms": {
    "FSAGS423": {
      "group": "fsags",
      "name": "FSAGS42.3",
      "pages": [
        1,
        2
      ]
    },
    "FSAGS421": {
      "group": "fsags421",
      "name": "FSAGS42.1",
      "pages": [
        6,
        7
      ]
    },
    "FSAGS551": {
      "group": "fsags551",
      "name": "FSAGS55.1",
      "pages": [
        9,
        10
      ]
    },
    "FSAGS09": {
      "group": "fsags09",
      "name": "FSAGS09",
      "pages": [
        11,
        12
      ]
    },
    "FSAGS208": {
      "group": "loading208",
      "name": "FSAGS208",
      "pages": [
        13
      ]
    },
    "BBBT": {
      "group": "bbbt",
      "name": "BBBT",
      "pages": [
        4
      ]
    }
  },
  "fields": {
    "1:arrRemarks": {
      "dx": 41,
      "dy": 10,
      "fs": 18,
      "hx": -28,
      "hy": -2,
      "hw": 90,
      "hh": 0
    },
    "1:acType": {
      "hw": 76,
      "hh": 4,
      "hx": -42,
      "hy": 1
    },
    "1:regn": {
      "hw": 82,
      "hh": 4,
      "hx": -35,
      "hy": 0
    },
    "1:date": {
      "hw": 64,
      "hh": 4,
      "hx": -27,
      "hy": 0
    },
    "1:yBag": {
      "hx": 0,
      "hy": -2,
      "hw": 20,
      "hh": -2
    },
    "1:arrMail": {
      "hx": -1,
      "hy": -3,
      "hw": 26,
      "hh": 0
    },
    "1:priorityBag": {
      "hx": -4,
      "hy": -3,
      "hw": 12,
      "hh": 0
    },
    "1:arrCargo": {
      "hx": 0,
      "hy": -2
    },
    "1:arrSpecial": {
      "hx": -32,
      "hy": -2,
      "hw": 66,
      "hh": 0
    },
    "1:transit": {},
    "1:topSTCH": {
      "hx": 18,
      "hy": 2,
      "hw": 6,
      "hh": -8,
      "fs": 19.5,
      "dx": 0,
      "dy": 6
    },
    "1:topVIP": {
      "hx": 24,
      "hy": 2,
      "hw": -12,
      "hh": -6,
      "fs": 19.5,
      "dx": 0,
      "dy": 6
    },
    "1:topINAD": {
      "hw": -12,
      "hh": -10,
      "hx": 8,
      "hy": 2,
      "dx": 0,
      "dy": 6,
      "fs": 18.5
    },
    "1:topUM": {
      "hw": 0,
      "hh": -12,
      "hx": 3,
      "hy": 2,
      "fs": 19.5,
      "dx": 0,
      "dy": 6
    },
    "1:topWCHR": {
      "hw": 0,
      "hh": -10,
      "hx": -14,
      "hy": 3,
      "dx": -2,
      "dy": 6,
      "fs": 18.5
    },
    "1:lirNotoc": {
      "hw": 200,
      "hh": 24,
      "hx": -93,
      "hy": -16,
      "dx": 0,
      "dy": -5,
      "fs": 26.2
    },
    "1:othersTop": {
      "dx": 47,
      "dy": 6,
      "fs": 18.5,
      "hx": -46,
      "hy": -1,
      "hw": 26,
      "hh": -4
    },
    "1:conveyorBefore": {
      "fs": 19,
      "dx": 0,
      "dy": 0
    },
    "1:offloadBagStart": {
      "hx": 15,
      "hy": 0,
      "hw": -12,
      "hh": 0,
      "dx": 5,
      "dy": 0,
      "fs": 17.5
    },
    "1:offloadCargoStart": {
      "hx": 16,
      "hy": 0,
      "hw": -10,
      "hh": 0,
      "dx": 5,
      "dy": 3
    },
    "1:arrDelayMins": {
      "dx": 4,
      "dy": 0,
      "hx": 6,
      "hy": 0
    },
    "1:h8Finish": {
      "hx": 0,
      "hy": 1,
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "1:h8Start": {
      "hw": 14,
      "hh": 4,
      "hx": 1,
      "hy": 1,
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "1:offloadInfo": {},
    "1:b1INF": {
      "fs": 18.7,
      "dx": 0,
      "dy": 3
    },
    "1:b1CHD": {
      "fs": 18.7,
      "dx": 0,
      "dy": 3
    },
    "1:b1ADL": {
      "fs": 19.7,
      "dx": 0,
      "dy": 3
    },
    "1:b2INF": {
      "fs": 19.7,
      "dx": 0,
      "dy": 3
    },
    "1:b2CHD": {
      "fs": 19.7,
      "dx": 0,
      "dy": 3
    },
    "1:b2ADL": {
      "fs": 18.7,
      "dx": 0,
      "dy": 4
    },
    "1:b3INF": {
      "fs": 18.7,
      "dx": 0,
      "dy": 4
    },
    "1:b3CHD": {
      "fs": 19.7,
      "dx": 0,
      "dy": 4
    },
    "1:b3ADL": {
      "fs": 19.7,
      "dx": 0,
      "dy": 4
    },
    "1:lmcDetails": {
      "hx": 1,
      "hy": -14,
      "hw": 4,
      "hh": 28,
      "fs": 22,
      "dx": 0,
      "dy": 0
    },
    "1:bottomVIP": {
      "dx": 0,
      "dy": 6,
      "fs": 18
    },
    "1:bottomSTCH": {
      "dx": 0,
      "dy": 7,
      "fs": 18
    },
    "1:bottomINAD": {
      "dx": 0,
      "dy": 7,
      "fs": 18
    },
    "1:bottomUM": {
      "fs": 18,
      "dx": 0,
      "dy": 6
    },
    "1:bottomWCHR": {
      "dx": 0,
      "dy": 6,
      "fs": 18
    },
    "1:depDelayMins": {
      "dx": 0,
      "dy": 7,
      "fs": 18,
      "hw": -4,
      "hh": 0,
      "hx": -3,
      "hy": 0
    },
    "1:depDelayReason": {
      "dx": 56.7,
      "dy": 7.6,
      "fs": 18.5,
      "hx": 31,
      "hy": 0
    },
    "1:depRemarks": {
      "dx": 32.2,
      "dy": 10,
      "fs": 19,
      "hx": 11,
      "hy": 0,
      "hw": 0,
      "hh": -16
    },
    "2:continuation": {
      "dx": -1.1,
      "dy": 0.2,
      "hw": 0,
      "hh": 16,
      "hx": 0,
      "hy": 21,
      "lines": {
        "0": {
          "align": "left",
          "dx": 0,
          "dy": -4,
          "fs": 18
        },
        "1": {
          "align": "left",
          "dx": 0,
          "dy": -6,
          "fs": 19
        },
        "2": {
          "align": "left",
          "dx": 0,
          "dy": -5,
          "fs": 19
        },
        "3": {
          "align": "left",
          "fs": 19
        }
      }
    },
    "2:airComments": {
      "hw": 0,
      "hh": -34,
      "hx": 1.1,
      "hy": 20,
      "lines": {
        "0": {
          "align": "left",
          "dx": 0,
          "dy": -4,
          "fs": 19
        },
        "1": {
          "dx": 0,
          "dy": -3,
          "align": "left",
          "fs": 19
        },
        "2": {
          "align": "left",
          "fs": 18,
          "dx": 0,
          "dy": -1
        },
        "3": {
          "align": "left",
          "fs": 18,
          "dx": 0,
          "dy": -1
        },
        "4": {
          "align": "left",
          "fs": 18,
          "dx": -1,
          "dy": 0
        },
        "5": {
          "fs": 18,
          "dx": 0,
          "dy": 1,
          "align": "left"
        }
      }
    },
    "2:representativeName": {
      "dx": 28.8,
      "dy": 4.1,
      "hw": -4,
      "hh": -8,
      "hx": 4,
      "hy": -2,
      "fs": 23.2,
      "align": "left"
    },
    "2:coordArrName": {
      "hw": 54,
      "hh": 0,
      "hx": -37.8,
      "hy": -3.3,
      "fs": 24.2,
      "dx": 33.3,
      "dy": -1.1,
      "align": "left"
    },
    "2:coordDepName": {
      "hw": 76,
      "hh": 0,
      "hx": -24.4,
      "hy": 0,
      "fs": 25.2,
      "align": "left",
      "dx": 40,
      "dy": -2.3
    },
    "1:estimatedBag": {
      "fs": 20.2,
      "dx": 0,
      "dy": -2
    },
    "1:bayBefore": {
      "dx": 3,
      "dy": -1
    },
    "1:redName": {
      "align": "left",
      "dx": 7,
      "dy": 2,
      "hx": -15,
      "hy": 0
    },
    "1:passengerStepAfter": {
      "fs": 18.6,
      "dx": 0,
      "dy": 0
    },
    "1:porterBefore": {
      "fs": 18.1,
      "dx": -4,
      "dy": 0
    },
    "1:operatorBefore": {
      "fs": 17.1,
      "dx": -2,
      "dy": 0
    },
    "1:porterAfter": {
      "fs": 18.2,
      "dx": 0,
      "dy": 1
    },
    "1:operatorAfter": {
      "dx": 0,
      "dy": 1,
      "fs": 17.2
    },
    "6:f421_depPaxTTL": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_depPaxC": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_depPaxY": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_depPaxI": {
      "dx": 1,
      "dy": 4
    },
    "6:f421_arrPaxTTL": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_arrPaxC": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_arrPaxY": {
      "dx": -0.1,
      "dy": 4
    },
    "6:f421_arrPaxI": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_route1": {
      "dx": 0,
      "dy": 3
    },
    "6:f421_route2": {
      "dx": 0,
      "dy": 3
    },
    "6:f421_route3": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_bookingF": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_bookingC": {
      "dx": -3,
      "dy": 3,
      "fs": 21.3,
      "align": "left"
    },
    "6:f421_bookingY": {
      "dx": 0,
      "dy": 4
    },
    "6:f421_std": {
      "fs": 20.9,
      "dx": 0,
      "dy": 4
    },
    "6:f421_sta": {
      "dx": -1,
      "dy": 4,
      "fs": 20.9
    },
    "6:f421_eta": {
      "fs": 22
    },
    "6:f421_etd": {
      "fs": 22,
      "dx": 0,
      "dy": 0
    },
    "6:f421_othersTop": {
      "lines": {
        "0": {
          "dx": -3,
          "dy": -7,
          "fs": 17
        }
      }
    },
    "6:f421_othersTop2": {
      "fs": 16.5,
      "dx": 0,
      "dy": -4
    },
    "6:f421_topWCHR": {
      "dx": 2,
      "dy": 2
    },
    "6:f421_topUM": {
      "dx": 2,
      "dy": 2
    },
    "6:f421_topINAD": {
      "dx": 2,
      "dy": 2
    },
    "6:f421_topSTCH": {
      "dx": 2,
      "dy": 2
    },
    "6:f421_topVIP": {
      "dx": 2,
      "dy": 2
    },
    "6:f421_h8Start": {
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "6:f421_h8Finish": {
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "6:f421_h7Start": {
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "6:f421_h6Start": {
      "dx": 0,
      "dy": 3,
      "fs": 20.2
    },
    "6:f421_h5Start": {
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "6:f421_arrRemarks": {
      "lines": {
        "0": {}
      }
    },
    "6:f421_h9Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h9Finish": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h10Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h10Finish": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h11Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h11Finish": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h12Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h13Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h14Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h15Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h16Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h17Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h17Finish": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h18Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h19Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h20Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h21Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h22Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h23Start": {
      "dx": 0,
      "dy": 2
    },
    "6:f421_h24Start": {
      "dx": -1.2,
      "dy": 2
    },
    "6:f421_b1TotalBags": {
      "dx": 0,
      "dy": 17.1,
      "fs": 26
    },
    "6:f421_b2TotalBags": {
      "dx": 0,
      "dy": 16.7,
      "fs": 26
    },
    "6:f421_b3TotalBags": {
      "dx": 2.2,
      "dy": 16.7,
      "fs": 26
    },
    "6:f421_b1ADL": {},
    "6:f421_b1TOTAL": {},
    "6:f421_boardTime1": {},
    "6:f421_b2INF": {},
    "6:f421_lmcDetails": {
      "lines": {
        "0": {
          "dx": 0,
          "dy": -18
        },
        "1": {
          "dx": 0,
          "dy": -19
        },
        "2": {
          "dx": 0,
          "dy": 4
        },
        "3": {
          "dx": 0,
          "dy": -18
        }
      }
    },
    "6:f421_bottomINAD": {
      "dx": 5,
      "dy": 0
    },
    "6:f421_bottomSTCH": {
      "dx": 5,
      "dy": 0
    },
    "6:f421_bottomVIP": {
      "dx": 6,
      "dy": 0
    },
    "6:f421_bottomUM": {
      "dx": 6,
      "dy": 0
    },
    "6:f421_bottomWCHR": {
      "dx": 6,
      "dy": 0
    },
    "6:f421_depDelayMins": {
      "dx": 6,
      "dy": 0
    },
    "6:f421_depDelayReason": {
      "dx": 5,
      "dy": 0
    },
    "7:f421_continuation": {
      "lines": {
        "0": {
          "dx": 0,
          "dy": -15
        },
        "1": {
          "dx": 0,
          "dy": -16
        },
        "2": {
          "dx": 0,
          "dy": -16
        },
        "3": {
          "dx": 0,
          "dy": -14
        },
        "4": {
          "dx": -1.1,
          "dy": -12
        },
        "5": {
          "dx": 0.1,
          "dy": -14.1
        }
      }
    },
    "7:f421_representativeName": {
      "dx": 2,
      "dy": -6,
      "fs": 25.5,
      "hx": -55.5,
      "hy": -12.3,
      "hw": 114,
      "hh": 10
    },
    "7:f421_coordArrName": {
      "hx": -48.1,
      "hy": -8.2,
      "hw": 106,
      "hh": 0,
      "dx": 0,
      "dy": -6,
      "fs": 24.3
    },
    "7:f421_coordDepName": {
      "hx": -49.9,
      "hy": -7.8,
      "hw": 98,
      "hh": 0,
      "dx": 0,
      "dy": -6,
      "fs": 26.3
    },
    "9:f551_date": {
      "dx": 8,
      "dy": 3,
      "fs": 20.8,
      "hx": 0,
      "hy": 4
    },
    "9:f551_fltBefore": {
      "dx": 21,
      "dy": 3,
      "fs": 20.8,
      "hx": 0,
      "hy": 4
    },
    "9:f551_fltAfter": {
      "fs": 21.8,
      "dx": 0,
      "dy": 6,
      "hx": -1.1,
      "hy": 2.9
    },
    "9:f551_regn": {
      "hx": 0,
      "hy": 4,
      "dx": 0,
      "dy": 6
    },
    "9:f551_route1": {
      "dx": 0,
      "dy": 6,
      "hx": 0,
      "hy": 4
    },
    "9:f551_route3": {
      "dx": 0,
      "dy": 5,
      "hx": 0,
      "hy": 4
    },
    "10:f551_handlingNotes": {
      "lines": {
        "0": {
          "fs": 18
        },
        "1": {
          "dx": 0,
          "dy": 12,
          "fs": 18
        },
        "2": {
          "dx": -1.1,
          "dy": 25.8,
          "fs": 19
        },
        "3": {
          "dx": 36.7,
          "dy": -114.5
        },
        "4": {
          "dx": 0,
          "dy": 9.9,
          "fs": 20
        },
        "5": {
          "dx": 0.4,
          "dy": 55.5,
          "fs": 18
        },
        "6": {
          "fs": 18,
          "dx": 0,
          "dy": 3
        }
      }
    },
    "10:f551_airlineComment": {
      "lines": {
        "0": {
          "fs": 18,
          "dx": 0,
          "dy": -1
        },
        "1": {
          "dx": 0,
          "dy": 12,
          "fs": 19
        },
        "2": {
          "dx": 0,
          "dy": 24,
          "fs": 19
        },
        "3": {
          "dx": 0,
          "dy": 27,
          "fs": 13
        }
      }
    },
    "10:f551_loadingStaffName": {
      "dx": 63.3,
      "dy": -1.1,
      "hx": 60,
      "hy": -1.1,
      "hw": 0,
      "hh": 18
    },
    "10:f551_engineerName": {
      "hw": 0,
      "hh": 18
    }
  }
};
