/* SAGS shared form layout · generated by AD · do not edit by hand */
window.SAGS_PUBLISHED_FORM_LAYOUT={
  "schema": 1,
  "build": "V3.72",
  "publishedAt": 1787392358595,
  "forms": [
    "fsags423",
    "fsags551"
  ],
  "fields": {
    "1:arrRemarks": {
      "dx": 41,
      "dy": 10,
      "fs": 18,
      "hx": -28,
      "hy": -2,
      "hw": 90,
      "hh": 0
    },
    "1:acType": {
      "hw": 76,
      "hh": 4,
      "hx": -42,
      "hy": 1
    },
    "1:regn": {
      "hw": 82,
      "hh": 4,
      "hx": -35,
      "hy": 0
    },
    "1:date": {
      "hw": 64,
      "hh": 4,
      "hx": -27,
      "hy": 0
    },
    "1:yBag": {
      "hx": 0,
      "hy": -2,
      "hw": 20,
      "hh": -2
    },
    "1:arrMail": {
      "hx": -1,
      "hy": -3,
      "hw": 26,
      "hh": 0
    },
    "1:priorityBag": {
      "hx": -4,
      "hy": -3,
      "hw": 12,
      "hh": 0
    },
    "1:arrCargo": {
      "hx": 0,
      "hy": -2
    },
    "1:arrSpecial": {
      "hx": -32,
      "hy": -2,
      "hw": 66,
      "hh": 0
    },
    "1:transit": {},
    "1:topSTCH": {
      "hx": 18,
      "hy": 2,
      "hw": 6,
      "hh": -8,
      "fs": 19.5,
      "dx": 0,
      "dy": 5
    },
    "1:topVIP": {
      "hx": 24,
      "hy": 2,
      "hw": -12,
      "hh": -6,
      "fs": 19.5,
      "dx": 0,
      "dy": 6
    },
    "1:topINAD": {
      "hw": -12,
      "hh": -10,
      "hx": 8,
      "hy": 2,
      "dx": 0,
      "dy": 6,
      "fs": 18.5
    },
    "1:topUM": {
      "hw": 0,
      "hh": -12,
      "hx": 3,
      "hy": 2,
      "fs": 19.5,
      "dx": 0,
      "dy": 6
    },
    "1:topWCHR": {
      "hw": 0,
      "hh": -10,
      "hx": -14,
      "hy": 3,
      "dx": -2,
      "dy": 6,
      "fs": 18.5
    },
    "1:lirNotoc": {
      "hw": 200,
      "hh": 24,
      "hx": -93,
      "hy": -16,
      "dx": 0,
      "dy": -5,
      "fs": 26.2
    },
    "1:othersTop": {
      "dx": 47,
      "dy": 6,
      "fs": 18.5,
      "hx": -46,
      "hy": -1,
      "hw": 26,
      "hh": -4
    },
    "1:conveyorBefore": {
      "fs": 15,
      "dx": 0,
      "dy": 0
    },
    "1:offloadBagStart": {
      "hx": 15,
      "hy": 0,
      "hw": -12,
      "hh": 0,
      "dx": 5,
      "dy": 0,
      "fs": 17.5
    },
    "1:offloadCargoStart": {
      "hx": 16,
      "hy": 0,
      "hw": -10,
      "hh": 0,
      "dx": 5,
      "dy": 3
    },
    "1:arrDelayMins": {
      "dx": 4,
      "dy": 0,
      "hx": 6,
      "hy": 0
    },
    "1:h8Finish": {
      "hx": 0,
      "hy": 1,
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "1:h8Start": {
      "hw": 14,
      "hh": 4,
      "hx": 1,
      "hy": 1,
      "dx": 0,
      "dy": 3,
      "fs": 19.5
    },
    "1:offloadInfo": {},
    "1:b1INF": {
      "fs": 18.7,
      "dx": 0,
      "dy": 3
    },
    "1:b1CHD": {
      "fs": 18.7,
      "dx": 0,
      "dy": 3
    },
    "1:b1ADL": {
      "fs": 19.7,
      "dx": 0,
      "dy": 3
    },
    "1:b2INF": {
      "fs": 19.7,
      "dx": 0,
      "dy": 3
    },
    "1:b2CHD": {
      "fs": 19.7,
      "dx": 0,
      "dy": 3
    },
    "1:b2ADL": {
      "fs": 18.7,
      "dx": 0,
      "dy": 4
    },
    "1:b3INF": {
      "fs": 18.7,
      "dx": 0,
      "dy": 4
    },
    "1:b3CHD": {
      "fs": 19.7,
      "dx": 0,
      "dy": 4
    },
    "1:b3ADL": {
      "fs": 19.7,
      "dx": 0,
      "dy": 4
    },
    "1:lmcDetails": {
      "hx": 1,
      "hy": -14,
      "hw": 4,
      "hh": 28,
      "fs": 22,
      "dx": 0,
      "dy": 0
    },
    "1:bottomVIP": {
      "dx": 0,
      "dy": 6,
      "fs": 18
    },
    "1:bottomSTCH": {
      "dx": 0,
      "dy": 7,
      "fs": 18
    },
    "1:bottomINAD": {
      "dx": 0,
      "dy": 7,
      "fs": 18
    },
    "1:bottomUM": {
      "fs": 18,
      "dx": 0,
      "dy": 6
    },
    "1:bottomWCHR": {
      "dx": 0,
      "dy": 6,
      "fs": 18
    },
    "1:depDelayMins": {
      "dx": 0,
      "dy": 7,
      "fs": 18,
      "hw": -4,
      "hh": 0,
      "hx": -3,
      "hy": 0
    },
    "1:depDelayReason": {
      "dx": 56.7,
      "dy": 7.6,
      "fs": 18.5,
      "hx": 31,
      "hy": 0
    },
    "1:depRemarks": {
      "dx": 32.2,
      "dy": 10,
      "fs": 19,
      "hx": 11,
      "hy": 0,
      "hw": 0,
      "hh": -16
    },
    "2:continuation": {
      "dx": -1.1,
      "dy": 0.2,
      "hw": 0,
      "hh": 16,
      "hx": 0,
      "hy": 21
    },
    "2:airComments": {
      "hw": 0,
      "hh": -34,
      "hx": 1.1,
      "hy": 20
    },
    "2:representativeName": {
      "dx": -118.9,
      "dy": 0,
      "hw": -4,
      "hh": -8,
      "hx": 4,
      "hy": -2
    },
    "2:coordArrName": {
      "hw": 54,
      "hh": 0,
      "hx": -37.8,
      "hy": -3.3,
      "fs": 23.2
    },
    "2:coordDepName": {
      "hw": 76,
      "hh": 0,
      "hx": -24.4,
      "hy": 0,
      "fs": 24.2
    }
  }
};
