const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html'),css=read('app/styles/new-ui-v1.css');
assert.match(html,/id="sags-ui-689-airline-dashboard"/);
assert.match(html,/HÃNG HÀNG KHÔNG/);
assert.match(html,/XEM TẤT CẢ/);
assert.match(html,/sagsReceiveAction/);
assert.match(css,/V6\.4\.89 · AIRLINE DASHBOARD \+ AD CONTRAST/);
assert.match(css,/#v503AdminResetPanel/);
assert.match(css,/\.sagsAdminPanel \.sagsAdminField > div > span/);
console.log('Airline dashboard + AD contrast UI contract passed');
