const assert=require('node:assert/strict');
const {server,client,settle}=require('./helpers/draft-harness.cjs');
const {IDBFactory}=require('fake-indexeddb');
const tests=[];const test=(name,fn)=>tests.push([name,fn]);
test('A -> B before 320ms retains immutable A path',async()=>{const s=server(),a=client(s);a.record('A draft');a.setFlight('B');await a.runTimers(320);assert.equal(s.writes.length,1);assert.match(s.writes[0].path,/roster_sessions\/A\/draftRecoveryV2\/USER\//);assert.equal(s.writes[0].value.flightSessionId,'A');assert.equal(a.read(),null)});
test('logout/login B: old transaction callback cannot write as B; A queue survives',async()=>{const s=server(),a=client(s);s.setHold(true);a.record('A draft');await settle();const p=a.flush();await settle();assert.equal(s.jobs.length,1);a.setUser('B');s.jobs.shift()();await p;assert.equal(s.writes.length,0);assert.equal((await a.rows())[0].pendingSync,true);a.setUser('USER');s.setHold(false);await a.flush();assert.equal(s.writes.length,1)});
test('timestamp 1/2 writes complete in reverse order atomically',async()=>{const s=server(),a=client(s,{now:1}),b=client(s,{now:2,writer:'tab-2'});s.setHold(true);a.record('older');b.record('newer');await settle();const p=a.flush(),q=b.flush();await settle();assert.equal(s.jobs.length,2);s.jobs.pop()();s.jobs.pop()();await Promise.all([p,q]);assert.equal([...s.values.values()][0].value,'newer');assert.equal([...s.values.values()][0].atMs,2)});
test('two tabs sharing IDB same timestamp deterministic tie-break',async()=>{const s=server(),db=new IDBFactory(),a=client(s,{db,writer:'a'}),b=client(s,{db,writer:'z'});a.record('a');b.record('z');await settle();await Promise.all([a.flush(),b.flush()]);assert.equal([...s.values.values()][0].value,'z');assert.equal((await a.rows())[0].value,'z')});
test('offline A queue reconnects while B is active',async()=>{const s=server(),a=client(s);a.c.navigator.onLine=false;a.record('offline A');await settle();await a.flush();assert.equal(s.writes.length,0);a.setFlight('B');a.c.navigator.onLine=true;await a.flush();assert.match(s.writes[0].path,/roster_sessions\/A\//);assert.equal(a.read(),null)});
test('late A pull does not inject into B or a different user',async()=>{for(const change of [a=>a.setFlight('B'),a=>a.setUser('B')]){const s=server(),a=client(s);const path='roster_sessions/A/draftRecoveryV2/USER';s.values.set(path,{x:{field:'field',part:'quickTime',flightSessionId:'A',rosterAssignmentId:'A',value:'remote A',atMs:3000}});s.setReadHold(true);const p=a.pull();await settle();change(a);s.releaseRead();assert.equal(await p,false);assert.equal(a.read(),null);assert.equal(a.restored.length,0)}});
test('new record wins older tombstone, newer tombstone wins old record',async()=>{for(const newerDeleted of [false,true]){const s=server(),a=client(s,{now:1}),b=client(s,{now:2,writer:'tab-2'});s.setHold(true);if(newerDeleted){a.record('old');b.forget()}else{a.forget();b.record('new')}await settle();const p=a.flush(),q=b.flush();await settle();s.jobs.pop()();s.jobs.pop()();await Promise.all([p,q]);const remote=[...s.values.values()][0];assert.equal(remote.deleted,newerDeleted);assert.equal(remote.atMs,2)}});
test('late acknowledgement never clears newer pending IDB record',async()=>{const s=server(),a=client(s);s.setHold(true);a.record('old');await settle();const p=a.flush();await settle();a.setClock(1001);a.record('new');await settle();s.jobs.shift()();await p;const row=(await a.rows())[0];assert.equal(row.value,'new');assert.equal(row.pendingSync,true);s.setHold(false);await a.flush();assert.equal([...s.values.values()][0].value,'new')});
test('server offset compensates a fast clock; same-tab clock rollback stays monotonic',async()=>{const s=server();s.setOffset(-10000);const a=client(s,{now:11000});a.record('first');await settle();await a.flush();assert.equal([...s.values.values()][0].atMs,1000);a.setClock(100);a.record('second');await settle();await a.flush();const r=[...s.values.values()][0];assert.equal(r.value,'second');assert.equal(r.atMs,1000);assert.equal(r.version.counter,1)});
test('pull does not overwrite a local edit that raced the remote read',async()=>{const s=server(),a=client(s);s.values.set('roster_sessions/A/draftRecoveryV2/USER',{x:{field:'field',part:'quickTime',flightSessionId:'A',rosterAssignmentId:'A',value:'remote',atMs:1}});s.setReadHold(true);const p=a.pull();a.record('local');await settle();s.releaseRead();await p;assert.equal(a.read().value,'local')});
test('legacy atMs queue retained through restart and syncs previous flight',async()=>{const s=server(),a=client(s);a.c.navigator.onLine=false;a.record('legacy');await settle();const row=(await a.rows())[0];delete row.version;row.schema=2;const db=await new Promise(res=>{const q=a.db.open('sags-draft-recovery-v2');q.onsuccess=()=>res(q.result)});await new Promise(res=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(row);tx.oncomplete=res});db.close();const b=client(s,{db:a.db,writer:'restart'});b.setFlight('B');await b.flush();assert.equal(s.writes[0].value.flightSessionId,'A');assert.equal(s.writes[0].value.value,'legacy')});
test('restart with clock rollback retains durable logical watermark',async()=>{const s=server(),db=new IDBFactory(),a=client(s,{db,now:1000});a.record('before restart');await settle();await a.flush();const b=client(s,{db,now:10,writer:'restart'});b.record('after restart');await settle();await b.flush();assert.equal([...s.values.values()][0].value,'after restart');assert.equal([...s.values.values()][0].atMs,1000)});
test('skew-corrected local mirror accepts a genuinely newer remote version',async()=>{const s=server();s.setOffset(-10000);const a=client(s,{now:11000});a.record('local');await settle();await a.flush();const [key,r]=[...s.values.entries()][0];s.values.set(key,{...r,value:'remote newer',atMs:2000,version:{atMs:2000,counter:0,writer:'remote'}});await a.pull();assert.equal(a.read().value,'remote newer')});
test('pre-existing foreign-flight cloud row never acknowledges or overwrites local pending draft',async()=>{const s=server(),a=client(s);a.record('local A');await settle();await a.flush();const [path,row]=[...s.values.entries()][0];s.values.set(path,{...row,flightSessionId:'B',value:'foreign B',atMs:99999});a.setClock(2000);a.record('new local A');await settle();await a.flush();assert.equal(s.values.get(path).value,'foreign B');assert.equal((await a.rows())[0].pendingSync,true);assert.match(a.c.sagsDraftV2Status().lastCloudError,/identity mismatch/)});
(async()=>{let fail=0;for(const [name,fn]of tests)try{await fn();console.log('PASS '+name)}catch(e){fail++;console.error('FAIL '+name,e)}console.log(`Draft behavioral: ${tests.length-fail} pass, ${fail} fail`);process.exitCode=fail?1:0})()
