const fs=require('node:fs'),assert=require('node:assert/strict');
const mod=fs.readFileSync(__dirname+'/../app/modules/form-entry-contrast.v1.js','utf8');
const index=fs.readFileSync(__dirname+'/../index.html','utf8');
const sw=fs.readFileSync(__dirname+'/../service-worker.js','utf8');
const ver=JSON.parse(fs.readFileSync(__dirname+'/../version.json','utf8'));
assert.equal(ver.build,JSON.parse(fs.readFileSync(__dirname+'/../asset-manifest.json','utf8')).build);
assert.match(mod,/#ffffff/);assert.match(mod,/#111111/);assert.match(mod,/#071c28/);
assert.match(mod,/-webkit-text-fill-color:var\(--sags-entry-fg\)!important/);
assert.match(mod,/contenteditable/);assert.match(mod,/:autofill/);assert.match(mod,/data-sags-entry-surface="blue"/);
assert.doesNotMatch(mod,/\.sheet svg|fn\.apply|patchOpeners/);
assert(index.includes('form-entry-contrast.v1.js?v='+ver.build),'contrast module must use current release query');
assert.match(sw,/\.\/app\/modules\/form-entry-contrast\.v1\.js/);
console.log('Entry-only contrast rule passed');
