const fs=require('node:fs'),assert=require('node:assert/strict');
const css=fs.readFileSync(__dirname+'/../app/styles/new-ui-v1.css','utf8');
const js=fs.readFileSync(__dirname+'/../app/modules/mobile-form-dock.v2.js','utf8');
const index=fs.readFileSync(__dirname+'/../index.html','utf8');
const sw=fs.readFileSync(__dirname+'/../service-worker.js','utf8');
const v=JSON.parse(fs.readFileSync(__dirname+'/../version.json','utf8'));
assert.equal(v.version,JSON.parse(fs.readFileSync(__dirname+'/../asset-manifest.json','utf8')).version);
assert.equal(v.displayVersion,JSON.parse(fs.readFileSync(__dirname+'/../asset-manifest.json','utf8')).version);
assert.equal(v.build,JSON.parse(fs.readFileSync(__dirname+'/../asset-manifest.json','utf8')).build);
assert.doesNotMatch(css,/V2\.5 BUILD 21|V2\.5 BUILD 22|V2\.5 TEST · MOBILE FORM DOCK/);
assert.match(css,/#v324HandoverBtn\{[\s\S]*?grid-column:1\/2!important;grid-row:2\/3!important/);
assert.match(css,/#v163SignBtn\{[\s\S]*?grid-column:2\/3!important;grid-row:2\/3!important/);
assert.match(js,/buttonLayout\(document\.getElementById\("v324HandoverBtn"\),"1 \/ 2","2 \/ 3"\)/);
assert.match(js,/buttonLayout\(document\.getElementById\("v163SignBtn"\),"2 \/ 3","2 \/ 3"\)/);
assert.match(js,/setProperty\(prop,value,"important"\)/);
assert.match(index,/sags-mobile-form-dock-v2/);
assert.doesNotMatch(index,/sags-mobile-form-dock-v1/);
assert.match(sw,/mobile-form-dock\.v2\.js/);
console.log('V2.6 canonical mobile dock contract passed');
