const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html'),js=read('app/modules/settings.v1.js'),css=read('app/styles/settings.v1.css'),sw=read('service-worker.js'),pref=read('app/modules/ui-preferences.v1.js'),ver=JSON.parse(read('version.json'));
assert.equal(ver.version,'V6.4.90');
assert.match(html,/settings\.v1\.js\?v=V6\.4\.90-20261006-SETTINGS-CENTER-01/);
assert.match(html,/settings\.v1\.css\?v=V6\.4\.90-20261006-SETTINGS-CENTER-01/);
assert.match(sw,/\.\/app\/modules\/settings\.v1\.js/);
assert.match(sw,/\.\/app\/styles\/settings\.v1\.css/);
assert.match(js,/preferencesV1/);
assert.match(js,/sagsOpenSettings/);
assert.match(js,/avatarData/);
assert.match(js,/sagsNotificationAllowed/);
assert.match(js,/Cloud Draft/);
assert.match(js,/Chưa có API server mặc định/);
assert.match(css,/sagsCustomGreeting/);
assert.match(pref,/applyTheme\(readTheme\(\),false\)/);
assert.match(pref,/const t=readTheme\(\);/);
assert.doesNotMatch(js,/currentUserProfile\s*=/);
console.log('Settings Center V6.4.90 contract passed');
