const fs=require('node:fs'),assert=require('node:assert/strict');
const boot=fs.readFileSync(__dirname+'/../app/generated/boot-group-4.js','utf8');
const v=JSON.parse(fs.readFileSync(__dirname+'/../version.json','utf8'));
assert.equal(v.build,JSON.parse(fs.readFileSync(__dirname+'/../asset-manifest.json','utf8')).build);
assert.match(boot,/sagsUpdateIncompleteWorkGuard/);
assert.match(boot,/roster_sessions\//);
assert.match(boot,/PART_COMPLETED/);
assert.match(boot,/Hãy bấm HOÀN TẤT trước khi cập nhật/);
assert.match(boot,/sagsQuickEntryStatus/);
console.log('Strict update guard contract passed');
