const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
const ver=JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8'));
const man=JSON.parse(fs.readFileSync(path.join(root,'asset-manifest.json'),'utf8'));
assert.match(ver.version,/^V2\.\d+(?:\.\d+)?$/,'release must be a V2 version');
assert.equal(ver.displayVersion,ver.version);
assert.ok(ver.build.startsWith(ver.version+'-'));
assert.equal(man.version,ver.version);
assert.equal(man.build,ver.build);
assert.ok(index.includes('sags-release-version" content="'+ver.version+'"'));
assert.ok(index.includes('loginReleaseVersion">'+ver.version+'<'));
assert.ok(index.includes('theme-contrast.v2.js?v='+ver.build));
assert.ok(sw.includes("DISPLAY_VERSION='"+ver.version+"'"));
assert.match(sw,/theme-contrast\.v2\.js/);
assert.ok(man.assets['./app/modules/theme-contrast.v2.js']?.sha256);
assert.ok(man.assets['./index.html']?.sha256);
assert.ok(man.assets['./service-worker.js']?.sha256);
console.log('V2.3 release contrast/cache contract passed');
