const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
const ver=JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8'));
const man=JSON.parse(fs.readFileSync(path.join(root,'asset-manifest.json'),'utf8'));
assert.equal(ver.version,'V2.3');
assert.equal(ver.displayVersion,'V2.3');
assert.equal(ver.build,'V2.3-20261008-FLIGHT-FORMS-PDF-STABILITY-01');
assert.equal(man.version,'V2.3');
assert.equal(man.build,'V2.3-20261008-FLIGHT-FORMS-PDF-STABILITY-01');
assert.match(index,/sags-release-version" content="V2\.3"/);
assert.match(index,/loginReleaseVersion">V2\.3</);
assert.match(index,/theme-contrast\.v2\.js\?v=V2\.3-20261008-FLIGHT-FORMS-PDF-STABILITY-01/);
assert.match(sw,/DISPLAY_VERSION='V2\.3'/);
assert.match(sw,/theme-contrast\.v2\.js/);
assert.ok(man.assets['./app/modules/theme-contrast.v2.js']?.sha256);
assert.ok(man.assets['./index.html']?.sha256);
assert.ok(man.assets['./service-worker.js']?.sha256);
console.log('V2.3 release contrast/cache contract passed');
