const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
const ver=JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8'));
const man=JSON.parse(fs.readFileSync(path.join(root,'asset-manifest.json'),'utf8'));
assert.match(ver.version,/^V2\.\d+(?:\.\d+)?$/,'release must be a V2 version');
assert.ok(ver.build.startsWith(ver.version+'-'),'version/build mismatch');
assert.equal(man.version,ver.version);
assert.equal(man.build,ver.build);
assert.ok(index.includes('admin-all-form-viewer.v1.js?v='+ver.build),'all-form viewer must be pinned to release');
assert.match(sw,/admin-all-form-viewer\.v1\.js/,'viewer must be in verified PWA bootstrap');
assert.ok(man.assets['./app/modules/admin-all-form-viewer.v1.js']?.sha256,'viewer checksum missing');
assert.ok(man.assets['./index.html']?.sha256);
assert.ok(man.assets['./service-worker.js']?.sha256);
console.log('V2.3 AD all-form release/cache contract passed');
